### ISSUE TITLE
Add CloudMade support

### ISSUE THREAD

**Issue by bergie** [nzjrs/osm-gps-map#11]
CloudMade is an OpenStreetMap-based map service that allows creation of customized map tiles (including selecting colors and what details to include on what zoom level).

It would be great if osm-gps-map could support loading map tiles from CloudMade in addition to regular OSM tile providers, as then app developers could style the maps to fit the visual style of their application.

http://cloudmade.com/

**Comment by johnny-bit** [comment]
Unfortunate as it is - cloudmade pivoted away from OSM: https://wiki.openstreetmap.org/wiki/CloudMade

However the example may well still be valid.
