### ISSUE TITLE
Map does not show OpenStreetMap credits

### ISSUE THREAD

**Issue by Germano0** [nzjrs/osm-gps-map#24]
I found out this software while discussing on http://darktable.org/redmine/issues/9586 about missing OSM credits. Darktable software is using osm-gps-map to show OSM maps, but on the map there are not OSM credits

http://wiki.openstreetmap.org/wiki/Legal_FAQ#3a._I_would_like_to_use_OpenStreetMap_maps._How_should_I_credit_you.3F

http://www.openstreetmap.org/copyright

**Comment by Germano0** [comment]
Hello, are there any news about fixing this issue?
Best regards

**Comment by nzjrs** [comment]
TBH I forgot about it..... so no news unfortunately. I guess a patch implementing it would not be too hard, but would probbably break ABI
