### ISSUE TITLE
Remove Yahoo Maps support as it has been discontinued

### ISSUE THREAD

**Issue by odel4y** [nzjrs/osm-gps-map#36]
Yahoo has [discontinued](http://yahoo.tumblr.com/post/120700756894/q2-2015-progress-report-on-our-product) its Maps service. So it is perhaps a good idea to remove that option from the code.

**Comment by sardemff7** [comment]
Removing such support will change API and ABI as the list of services is in `osm-gps-map-source.h` which is installed.

@nzjrs Is it acceptable or not? I can make a PR for it if it is ok.

**Comment by nzjrs** [comment]
Yeah, please go ahead an make a PR.

Thanks!
