### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sardemff7** [nzjrs/osm-gps-map#40]
It may be the time for a new release. 1.0.3? 1.1?

**Comment by nzjrs** [comment]
Makes sense. I am stuck on LTS releases at work, so I haven't really tested
this against newer Gtk in a while.

If you can confirm it still works then I am happy to make a release.

**Comment by sardemff7** [comment]
Tested on Exherbo with darktable (1.7.0+1781~g105a614) and:
- GLib 2.44.0
- GTK+ 3.16.2
- Cairo 1.14.0
- Pango 1.3.8

I am a few minor versions behind upstream but it should definitely work.

Once #41 is merged, you can do the release commit and tag. Do not forget to update `LT_VERSION_INFO`!

**Comment by nzjrs** [comment]
Ok, thanks. I will try to do it tonight

**Comment by dreadnought** [comment]
Can we make another release, what do you think?

So far we have:
- fixed introspection issues (#44)
- updated (#46) and customizable HTTP user-agent (#47)
- copyright info (#48)

Now it should be more conform with the OpenStreetMaps Tile usage policy and others.

I made tests with Ubuntu 14.04 (current LTS), 16.04 (next LTS), and Mac OSX (using brew.sh).

**Comment by drahnr** [comment]
I can do some testing on Fedora 23 if that is desired.

**Comment by dreadnought** [comment]
It would be great to have a new osm-gps-map version for the next Linux distribution releases. The last one is one year old now and a new release would help to get the changes out to the users.

**Comment by bittner** [comment]
Any update on this?

**Comment by simon04** [comment]
I'm using osm-gps-map inside darktable. Today I wondered why OSM zoom 19 is not available which has been added via https://github.com/nzjrs/osm-gps-map/pull/62/commits/7e777e4f79296c66c32900e2a93fc6dbda3f1f78 – @nzjrs, please craft a new release of this very helpful library. :rocket:

**Comment by johnny-bit** [comment]
I'll be working towards creating new release.

@dreadnought - since you contributed quite a lot, can you help me a bit?

**Comment by dreadnought** [comment]
Great to hear that. I see that you are already checking the open issues. Where do you need help?

**Comment by johnny-bit** [comment]
I'm having trouble with introspection stuff. I'm just "a coder", so I never dug into gobject introspection stuff. Current master with relatively recent build env claims following introspection problems:

```
osm-gps-map-osd.h:30: Warning: OsmGpsMap: symbol='OSM_IS_GPS_MAP_OSD': Unknown namespace for symbol 'OSM_IS_GPS_MAP_OSD'
osm-gps-map-osd.h:31: Warning: OsmGpsMap: symbol='OSM_IS_GPS_MAP_OSD_CLASS': Unknown namespace for symbol 'OSM_IS_GPS_MAP_OSD_CLASS'
osm-gps-map-track.h:34: Warning: OsmGpsMap: symbol='OSM_IS_GPS_MAP_TRACK': Unknown namespace for symbol 'OSM_IS_GPS_MAP_TRACK'
osm-gps-map-track.h:35: Warning: OsmGpsMap: symbol='OSM_IS_GPS_MAP_TRACK_CLASS': Unknown namespace for symbol 'OSM_IS_GPS_MAP_TRACK_CLASS'
osm-gps-map-polygon.h:33: Warning: OsmGpsMap: symbol='OSM_IS_GPS_MAP_POLYGON': Unknown namespace for symbol 'OSM_IS_GPS_MAP_POLYGON'
osm-gps-map-polygon.h:34: Warning: OsmGpsMap: symbol='OSM_IS_GPS_MAP_POLYGON_CLASS': Unknown namespace for symbol 'OSM_IS_GPS_MAP_POLYGON_CLASS'
osm-gps-map-image.h:34: Warning: OsmGpsMap: symbol='OSM_IS_GPS_MAP_IMAGE': Unknown namespace for symbol 'OSM_IS_GPS_MAP_IMAGE'
osm-gps-map-image.h:35: Warning: OsmGpsMap: symbol='OSM_IS_GPS_MAP_IMAGE_CLASS': Unknown namespace for symbol 'OSM_IS_GPS_MAP_IMAGE_CLASS'
osm-gps-map-widget.h:36: Warning: OsmGpsMap: symbol='OSM_IS_GPS_MAP': Unknown namespace for symbol 'OSM_IS_GPS_MAP'
osm-gps-map-widget.h:37: Warning: OsmGpsMap: symbol='OSM_IS_GPS_MAP_CLASS': Unknown namespace for symbol 'OSM_IS_GPS_MAP_CLASS'
```

On my roadmap there's:
- Fixing deprecated stuff (a bit of that...)
- settiung up GithubActions for builds (since travis got limited a bit)
- prepare release :)

**Comment by johnny-bit** [comment]
Well... It's not so bad tbh...

There are only 3 things on my mind before doing release:
1. `g_type_class_add_private` and `G_TYPE_INSTANCE_GET_PRIVATE` are deprecated in favour of `G_ADD_PRIVATE()` and the generated `your_type_get_instance_private()` stuff. There's quite a bit of `private` stuff going on in osm-gps-map and I'm not yet confident enough in it to go around changing it ;)
2. I wonder about https://github.com/nzjrs/osm-gps-map/issues/59 and mentioned https://wiki.gnome.org/Projects/GnomeCommon/Migration - seems like a VERY GOOD IDEA tbh.
3. With what version number to make release? There were some small api chanes, namely some methods added and property changes etc so i'd propose `1.2.0`

If anyone can help with points 1&2 I would love that!

**Comment by dreadnought** [comment]
1. I didn't look at it yet, but I can. I suggest that you open new issues for problems that you see and can't solve on your own. This way it's clear what the open tasks are and who is working on them.
2. Is solved in # #75.
3. I would call it `1.2.0` too, as it adds new functions and is also the first release after 5 years.

I also like the idea of switch of using Github Actions, the migration should be as easy as taking the commands from the `.travis.yml`.

**Comment by johnny-bit** [comment]
Thanks @dreadnought !
1. Opened task #76 - feel free to check it :)
2. Thanks!
3. OK, let's go for `1.2.0` then :)

On a side note - GH actions is now ready and working :)

**Comment by johnny-bit** [comment]
Great news everyone!

Release 1.2.0 is ready!

https://github.com/nzjrs/osm-gps-map/releases/tag/1.2.0

Let's keep the project going!
