### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by cyber-wolf23** [nzjrs/osm-gps-map#43]
When building from source I am able to get as far as make but then it encounters an error, listed below, that I would appreciate help with. I am running Ubuntu 15.10.

osm-gps-map-track.h:93: Error: OsmGpsMap: identifier not found on the first line:
 *
  ^
osm-gps-map-track.c:231: Warning: OsmGpsMap: incorrect number of parameters in comment block, parameter annotations will be ignored.
osm-gps-map-polygon.h:56: Warning: OsmGpsMap: osm_gps_map_polygon_get_track: return value: Missing (transfer) annotation

**Comment by johnny-bit** [comment]
Seems fixed with #44
