### ISSUE TITLE
Add glade catalog file

### ISSUE THREAD

**Issue by drahnr** [nzjrs/osm-gps-map#51]
Add a glade catalog file for easy use with glade https://developer.gnome.org/gladeui/stable/catalogintro.html

**Comment by programmin1** [comment]
That would make it able to be used in GUI builder? That would be great, better than manually coding vbox/hbox, add, pack_start...

**Comment by dakk** [comment]
For those in need of it, I created a basic catalog file for glade.

![image](https://user-images.githubusercontent.com/1060425/101282308-bb4e5700-37d4-11eb-8544-631d3146d106.png)

**Comment by programmin1** [comment]
Perhaps the demo .py should be loading this one, .glade file is better than manually building everything?

**Comment by dakk** [comment]
Sure, a demo using glade could bè helpful
