### ISSUE TITLE
File collisions between 0.7.3 and 1.1.0

### ISSUE THREAD

**Issue by mkszuba** [nzjrs/osm-gps-map#55]
Hello,

Unfortunately there are file collisions between the two releases which prevent GTK+2 and GTK+3 versions of osm-gps-map from being installed completely in parallel. Namely:
- both versions install their documentation to /.../gtk-doc/html/libosmgpsmap .  I would suggest changing the directory name used by GTK+3 releases to libosmgpsmap-1.0, same as it was done elsewhere;
- the GObject introspection files are called OsmGpsMap-1.0.gir and OsmGpsMap-1.0.typelib for both versions. For consistency it should be called just OsmGpsMap.\* for GTK+2 releases, however I do not know if it is allowed for those files not to include a version number.

**Comment by johnny-bit** [comment]
No help can be done for 0.7 unfortunately and 1.x has set it's course... Plus most distros don't even carry 0.7 so we're in good spot I think
