### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by ph0dv** [nzjrs/osm-gps-map#58]
I cloned the files with:

git clone git://github.com/nzjrs/osm-gps-map

But i'm not sure how to compile.

root@ph0dv://osm-gps-map# ./configure.ac
bash: ./configure.ac: Toegang geweigerd

(Meaning access denied) I'm root?

Any suggestions?

**Comment by ph0dv** [comment]
I have installed autoconf (not sure if this is the way to go).

>>apt-get install autoconf

Then i run autonf in the map >>osm-gps-map

root@ph0dv://osm-gps-map# autoconf
configure.ac:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:13: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:15: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:16: error: possibly undefined macro: AM_PROG_LIBTOOL
configure.ac:18: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:42: error: possibly undefined macro: AM_CONDITIONAL

I get these errors

Kind regards,

Dick

**Comment by dreadnought** [comment]
Hi,
you have to run `./autogen.sh` first to generate all necessary files, please try this.

**Comment by ph0dv** [comment]
Installed:
apt-get install autogen autoconf libtool

perl: warning: Falling back to a fallback locale ("nl_NL.UTF-8").
automake: error: cannot open < gtk-doc.make: Bestand of map bestaat niet
autoreconf: automake failed with exit status: 1

**Comment by ph0dv** [comment]
>>you have to run ./autogen.sh first to generate all necessary files, please try this.
Ok did that withouth errors.

**Comment by ph0dv** [comment]
./configure
configure: error: Package requirements (libsoup-2.4) were not met:
No package 'libsoup-2.4' found

Have to fix this dependency first i guess.

**Comment by dreadnought** [comment]
This should install the needed dependencies:
`apt-get install gnome-common gtk-doc-tools libglib2.0-dev libgtk-3-dev libsoup2.4-dev libgirepository1.0-dev`

**Comment by ph0dv** [comment]
Thanks... did do the job!
