### ISSUE TITLE
Not able to run the code on windows 10, Python 2.7

### ISSUE THREAD

**Issue by GISConsortium** [nzjrs/osm-gps-map#60]
I am not able to resolve, "from gi.repository import OsmGpsMap" in mapViewer.py file. Actually, I am not able to get gi.repository.  All help will be appreciated.

Thanks

**Comment by Awaz41** [comment]
i don't know if you still in that problem, but for future users who have this issue go to this link: https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-getting-started

**Comment by johnny-bit** [comment]
A recently merged PR #65 with updated install instructions, mentions needing to install `gir1.2-osmgpsmap-1.0` package to have gir based python bindings. Dunno if it'll work with python 2.7 tho, since pythn 3.x is all the rage nowadays...

**Comment by programmin1** [comment]
It seems like MSYS2 should have it but it seems uninstallable :(
https://github.com/msys2/MINGW-packages/issues/10703
