### ISSUE TITLE
Missing TLS certificate verification when built with ancient libsoup

### ISSUE THREAD

**Issue by mcatanzaro** [nzjrs/osm-gps-map#85]
Hi, osm-gps-map-widget.c does not appear to be enabling TLS certificate verification on the SoupSessionAsync object it creates when built against libsoup older than 2.42. [You have to do this manually when using the deprecated SoupSessionAsync.](https://blogs.gnome.org/mcatanzaro/2021/05/25/reminder-soupsessionsync-and-soupsessionasync-default-to-no-tls-certificate-verification/)

I figure this should affect almost nobody in 2021, since libsoup 2.42 is old now, but I'm reporting it anyway because, well, the code is still there.

**Comment by johnny-bit** [comment]
Looks like the best bet would be to drop support for libsoup older than 2.42
