### ISSUE TITLE
Port to libsoup3

### ISSUE THREAD

**Issue by bulvara** [nzjrs/osm-gps-map#96]
Hi nzjrs,

it would be terrific if you could port osm-gps-map to libsoup3.

In soup3 the _struct_ SoupMessage can no longer be accessed and is [replaced by getters and setters](https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html).

**Comment by programmin1** [comment]
On what version was this released? Homepage still says libsoup2.4. https://nzjrs.github.io/osm-gps-map/
